language: node_js
node_js:
  - "8"
  - "10"
  - "12"
dist: trusty
services:
  - mongodb
  - redis-server
env:
  - NODE_ENV=test
  - TEST_CI_DB_URL=mongodb://127.0.0.1:27017/CITestTripped
  - ACCESS_TOKEN=trippedAcessToken
  - REFRESH_TOKEN=trippedRefreshToken
  - PORT=3000
  -
cache:
  directories:
    - node_modules
install:
  - yarn install
script:
  - sleep 3
  - yarn test:unit
