language: node_js
node_js:
  - "10"
  - "12"
dist: trusty
services:
  - mongodb
  - redis-server
env:
  - NODE_ENV=ci_test
cache:
  directories:
    - node_modules
install:
  - yarn install
script:
  - sleep 3
  - yarn test
